version: 2

jobs:
  test_py36_dj20: &test-template
    docker:
      - image: circleci/python:3.6
    environment:
      TOXENV: py36-django20
    steps:
      - checkout
      - run: sudo pip install tox
      - run: poetry install
      - run: tox

  test_py36_dj21:
    <<: *test-template
    docker:
      - image: circleci/python:3.6
    environment:
      TOXENV: py36-django21

  test_py37_dj20:
    <<: *test-template
    docker:
      - image: circleci/python:3.7
    environment:
      TOXENV: py37-django20

  test_py36_dj21:
    <<: *test-template
    docker:
      - image: circleci/python:3.7
    environment:
      TOXENV: py37-django21

workflows:
  version: 2
  test:
    jobs:
      - test_py36_dj20
      - test_py36_dj21
      - test_py37_dj20
      - test_py37_dj21
