version: 2

jobs:
  test_py38_dj30: &test-template
    docker:
      - image: circleci/python:3.8
    environment:
      TOXENV: py38-django30
    steps:
      - checkout
      - run: sudo pip install tox
      - run: poetry install
      - run: tox

  test_py38_dj21:
    <<: *test-template
    docker:
      - image: circleci/python:3.8
    environment:
      TOXENV: py38-django21

  test_py37_dj30:
    <<: *test-template
    docker:
      - image: circleci/python:3.7
    environment:
      TOXENV: py37-django30

  test_py37_dj21:
    <<: *test-template
    docker:
      - image: circleci/python:3.7
    environment:
      TOXENV: py37-django21

workflows:
  version: 2
  test:
    jobs:
      - test_py38_dj30
      - test_py38_dj21
      - test_py37_dj30
      - test_py37_dj21
